# Generated by Django 2.2.16 on 2020-09-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='campaign',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AdCampaign'),
        ),
    ]
